language: php

notifications:
  email: true

php:
  - 7.4
  - 8.0
#  - hhvm
#  - nightly

before_script:
  - composer install --dev
  - composer phplint
  - composer build-dev

#script:
#  - php vendor/bin/phpunit --coverage-clover ./test/logs/clover.xml

after_script:
  - php build/xspf.phar version -v
