language: php

notifications:
  email: true

php:
  - 7.4
  - 8.0
  - nightly

before_script:
  - chmod +x bin/*
  - bin/travis.sh before

script:
  - bin/travis.sh run

after_script:
  - bin/travis.sh after
