<?php
// @autogenerated
return [
    "Xspf\\Commands\\BatchCommand",
    "Xspf\\Commands\\Batch\\BatchConcurrentCommand",
    "Xspf\\Commands\\CleanCommand",
    "Xspf\\Commands\\CreateCommand",
    "Xspf\\Commands\\Duplicates\\ListDuplicatesCommand",
    "Xspf\\Commands\\Duplicates\\ShowDuplicatesCommand",
    "Xspf\\Commands\\File\\CopyCommand",
    "Xspf\\Commands\\File\\DeleteCommand",
    "Xspf\\Commands\\Index\\ConvertIndexCommand",
    "Xspf\\Commands\\Index\\CreateIndexCommand",
    "Xspf\\Commands\\Index\\CreateIndexPlaylistCommand",
    "Xspf\\Commands\\Index\\ExtractIndexCommand",
    "Xspf\\Commands\\Index\\FilterIndexCommand",
    "Xspf\\Commands\\Index\\OrderIndexCommand",
    "Xspf\\Commands\\MergeCommand",
    "Xspf\\Commands\\OrderCommand",
    "Xspf\\Commands\\SelfUpdateCommand",
    "Xspf\\Commands\\UpdateCommand",
    "Xspf\\Commands\\ValidateCommand",
    "Xspf\\Commands\\VersionCommand"
];
