<?php
// @autogenerated
return [
    "Xspf\\Commands\\BatchCommand",
    "Xspf\\Commands\\Batch\\BatchParallelCommand",
    "Xspf\\Commands\\CleanCommand",
    "Xspf\\Commands\\CreateCommand",
    "Xspf\\Commands\\File\\CopyCommand",
    "Xspf\\Commands\\Index\\ConvertIndexCommand",
    "Xspf\\Commands\\Index\\CreateIndexCommand",
    "Xspf\\Commands\\Index\\OrderIndexCommand",
    "Xspf\\Commands\\MergeCommand",
    "Xspf\\Commands\\OrderCommand",
    "Xspf\\Commands\\SelfUpdateCommand",
    "Xspf\\Commands\\UpdateCommand",
    "Xspf\\Commands\\ValidateCommand",
    "Xspf\\Commands\\VersionCommand"
];
