<?php
// @autogenerated
return [
    "Xspf\\Console\\Command\\BatchCommand",
    "Xspf\\Console\\Command\\Batch\\BatchConcurrentCommand",
    "Xspf\\Console\\Command\\CleanCommand",
    "Xspf\\Console\\Command\\CreateCommand",
    "Xspf\\Console\\Command\\Duplicates\\ListDuplicatesCommand",
    "Xspf\\Console\\Command\\Duplicates\\ShowDuplicatesCommand",
    "Xspf\\Console\\Command\\File\\CopyCommand",
    "Xspf\\Console\\Command\\File\\DeleteCommand",
    "Xspf\\Console\\Command\\Index\\ConvertIndexCommand",
    "Xspf\\Console\\Command\\Index\\CreateIndexCommand",
    "Xspf\\Console\\Command\\Index\\CreateIndexPlaylistCommand",
    "Xspf\\Console\\Command\\Index\\ExtractIndexCommand",
    "Xspf\\Console\\Command\\Index\\FilterIndexCommand",
    "Xspf\\Console\\Command\\Index\\OrderIndexCommand",
    "Xspf\\Console\\Command\\MergeCommand",
    "Xspf\\Console\\Command\\OrderCommand",
    "Xspf\\Console\\Command\\SelfUpdateCommand",
    "Xspf\\Console\\Command\\UpdateCommand",
    "Xspf\\Console\\Command\\ValidateCommand",
    "Xspf\\Console\\Command\\VersionCommand",
];
